version: '3.8'
services:
  overpass:
    # specify the image here
    image: ghcr.io/gis-ops/overpass:0.7.59.1
    container_name: overpass
    # uncomment if you want to build the image yourself
    # build: .
    ports:
      - 31942:80
    volumes:
      # use a docker managed volume
      - ./data:/db
    environment:
      - OVERPASS_META=no
      - OVERPASS_MODE=init
      - OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/germany-latest.osm.bz2
      - OVERPASS_DIFF_URL=http://download.geofabrik.de/europe/germany-updates/
      - OVERPASS_UPDATE_SLEEP=86400  # daily
      - OVERPASS_STOP_AFTER_INIT=false
      - OVERPASS_USE_AREAS=false
    healthcheck:
      test: ["CMD-SHELL", "curl -qf 'http://localhost/api/interpreter?data=[out:json];node(10106953094);out;' | jq '.generator' |grep -q Overpass || exit 1"]
      start_period: 24h
